version: '3.2'

services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: piston_api
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston:/piston
        tmpfs:
            - /piston/jobs:exec
            - /tmp:exec
